dapuzzo:
  allowed-origins: http://localhost:8080,http://localhost:3000
  mail:
    from: ${FROM_EMAIL_ADDRESS}
    subject: LOCAL Luke D'Apuzzo Website Contact

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/test
    password: pwd
    username: user