spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${LUKE_EMAIL_ADDRESS}
    password: ${LUKE_EMAIL_PASSWORD}
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migrations
    clean-on-validation-error: false


dapuzzo:
  mail:
    from: ${FROM_EMAIL_ADDRESS}
    subject: ${EMAIL_SUBJECT:Luke D'Apuzzo Website Contact}
    mailgun:
      password: ${MAILGUN_PASSWORD}
      username:  ${MAILGUN_USERNAME}
      url:  ${MAILGUN_URL}